
== Actions & challenges
An action is defined by a series of challenges and movement that a player can perform until he runs out of paces of Jog to use or has an action ending Shift of Momentum event. Note: a player's action includes another player trying to catch any Throw that he performs. When a player attempts to perform any type of physical activity which requires a dice roll to determine whether it is a success or failure, it is referred to as a challenge.

In order to attempt a challenge, you roll a number of challenge dice equal to the attribute for that challenge with a given number of successes needed for that challenge (if the number of successes needed is less than 1 then the challenge is treated as needing 1 success). Every challenge die which rolls a conditional success must be rolled again with the new result adding to list of rolls. Any die which rolls a conditional success on the second roll continues being rolled and added to the list of rolls until each rolls a result other than a conditional success. (Note: using spare dice or blank rolls is a great way to roll for conditional successes without remembering the other dice rolls).

NOTE: Example: You attempt to pick up the ball from the playing field with one standing opponent in an adjacent hex with a player with a Skill attribute of 4. You need two successes to pick up the ball. You roll 4 dice due to your Skill attribute and roll a flop(), blank () and 2 conditional success (). You roll the two dice with conditional successes again and roll a blank() and a conditional sucess(). One more roll of the die that was a conditional success results in a success (). This means for this challenge you rolled a flop, 2 blanks, a success, and 3 conditional successes for a total of 3 successes (1 success + 3 conditional successes - 1 flop) which enables the player to successfully pick up the ball.

You must also keep track of the number of dice which roll a flop. If a challenge results in more flops than successes, the player has "flopped" the challenge, usually with disastrous results.

NOTE: Example: You attempt to pick up the ball from the playing field with no players adjacent to it with a player with a Skill attribute of 3 thus you need one success. You roll a flop, a blank, and a conditional success. You roll the conditional success again and roll a flop. For this challenge you have rolled two flops, a blank, and a conditional success and so you  have flopped the challenge as you have two flops and only one success.
