== Actions & Défis

Une action est définie par une série de défis et de mouvements que le joueur peut effectuer jusqu'à ce qu'il n'est plus de point de Mouvement ou que son action se termine sur un Revirement de Situation (cf Temps fort). Note: Quand un joueur lance la balle, la réception d’un autre joueur fait partit de la même action. Quand un joueur tente de réaliser une activité physique nécessitant un jet de dé pour déterminé si il réussit ou échoue, c'est un défi.

Pour effectuer un défi, vous devez lancer un nombre de dé égal à l’attribut correspondant au défi et obtenir un nombre de succès  nécessaire pour réussir le défi. (On traite toute difficulté inférieure à 1 comme demandant un succès). Chaque dé qui donne un succès conditionnel doit être relancé et le nouveau résultat ajouté aux jets déjà obtenu. Chaque dé qui donne un succès conditionnel sur ce second jet est relancé et ajouté aux jets déjà obtenu jusqu'à ce que le résultat soit autre chose qu'un succès conditionnel.

TIP: : utiliser des dès de rechange ou les dés sans résultat est un bon moyen pour relancer les succès conditionnel sans oublier les résultats des autres jets

NOTE:

Vous devez garder une trace du nombre de dé qui donne un fiasco. Si le nombre de fiasco est plus important que le nombre de succès, le joueur a échoué, entrainant des résultats parfois désastreux.

NOTE: Vous essayer de Ramasser la balle sur le terrain sans adversaire autour de vous, votre attribut d'Habilité est de 3 et vous avez besoin d'un succès. Vous jeter un fiasco, un vide et un succès conditionnel. Vous relancez le succès conditionnel et vous obtenez un fiasco. Pour ce défi vous avez jeté deux fiascos, un vide et un succès conditionnel, vous échouez au défi puisque vous avez deux fiascos et seulement un succès.


----

 Actions & challenges
An action is defined by a series of challenges and movement that a player can perform until he runs out of paces of Jog to use or has an action ending Shift of Momentum event. Note: a player's action includes another player trying to catch any Throw that he performs. When a player attempts to perform any type of physical activity which requires a dice roll to determine whether it is a success or failure, it is referred to as a challenge.

In order to attempt a challenge, you roll a number of challenge dice equal to the attribute for that challenge with a given number of successes needed for that challenge (if the number of successes needed is less than 1 then the challenge is treated as needing 1 success). Every challenge die which rolls a conditional success must be rolled again with the new result adding to list of rolls. Any die which rolls a conditional success on the second roll continues being rolled and added to the list of rolls until each rolls a result other than a conditional success. (Note: using spare dice or blank rolls is a great way to roll for conditional successes without remembering the other dice rolls).

 Example: You attempt to pick up the ball from the playing field with one standing opponent in an adjacent hex with a player with a Skill attribute of 4. You need two successes to pick up the ball. You roll 4 dice due to your Skill attribute and roll a flop(), blank () and 2 conditional success (). You roll the two dice with conditional successes again and roll a blank() and a conditional sucess(). One more roll of the die that was a conditional success results in a success (). This means for this challenge you rolled a flop, 2 blanks, a success, and 3 conditional successes for a total of 3 successes (1 success + 3 conditional successes - 1 flop) which enables the player to successfully pick up the ball.

You must also keep track of the number of dice which roll a flop. If a challenge results in more flops than successes, the player has "flopped" the challenge, usually with disastrous results.

 Example: You attempt to pick up the ball from the playing field with no players adjacent to it with a player with a Skill attribute of 3 thus you need one success. You roll a flop, a blank, and a conditional success. You roll the conditional success again and roll a flop. For this challenge you have rolled two flops, a blank, and a conditional success and so you  have flopped the challenge as you have two flops and only one success.
----
