== Types de défis

Quand un joueur effectue une action, il peut choisir différents types de défis. Le joueur actif peut tenter chaque défi (autre que charger/Plaquer et pousser) autant de fois qu’il le désire durant son action. A chaque déplacement  du joueur d’un hexagone à un autre il utilise un de ces points de mouvement. Tenter un défi ne consomme aucun point de mouvement et vous pouvez tenter des défis après avoir utilisé le dernier point de mouvement. La liste suivante montre les types de défi:

*Se désengager* : se déplacer sur un hexagone adjacent avec un adversaire qui vous fait face. +
*Ramasser* : Ramasser la balle après s’être déplacé sur l’hexagone  dans lequel elle est au sol. +
*Lancer* : Lancer la balle à un autre joueur. Un joueur ne peut pas bouger ou entreprendre un  défi avant ou après un lancer de plus de 7 hexagones. +
*Charger/Plaquer* : Une fois par action vous pouvez Plaquer un adversaire sur un hexagone adjacent. +
*Pousser* : tenter de pousser un adversaire dans l’hexagone adjacent inoccupée directement derrière lui. Le nombre de Pousser est limité à la moitié de votre Mouvement (arrondi supérieur).
Réceptionner/Intercepter: attraper la balle lancer dans votre hexagone ou la passe ratée d’un adversaire qui passe dans votre hexagone. +
*Se lancer* : c’est un défi qui ne peut être tenté qu’une fois par action. Quand votre action normale est finit si vous avez des marqueurs de Temps fort de cotés vous pouvez tenté un défi Se lancer pour finir votre action. Un succès vous permet de réaliser un défi supplémentaire avec un dé supplémentaire ou un Plaquer/Pousser supplémentaire ou de vous déplacer d'un hexagone supplémentaire (incluant le désengager/ramasser si nécessaire) +

----
 Challenge types
When a player performs an action he may perform many different challenges. The active player may perform each challenge (other than Impact/Tackle and Shove) as many times as desired per action. Each time a player moves from one hex to another he uses one pace of his Jog. Performing challenges does not use any paces of Jog and can be performed even after using your last pace of Jog. The list below shows the types of challenges:

*Disengaging* - Move away from an adjacent hex with an opponent.
*Pick-up* - Attempting to pick up the elfball after moving into the hex where it is laying on the ground.

*Throw* - Attempting to throw the ball to another player. A player may not move or attempt a challenge before or after a throw of 7 or more hexes.
*Impact/Tackle* - Once per an action you may attempt to tackle an opponent in an adjacent hex.
*Shove* - Attempting to shove one opposing player into the unoccupied adjacent hex directly behind him. Shoves are limited to half your Jog (rounded up)
*Dash* - This is a special challenge that may be performed only once an action. After your normal action is ended (including performing any challenges at the end), if you have Momentum counters left you can attempt a Dash challenge to extend your action. A successful Dash challenge lets you either perform one additional challenge with one extra Challenge dice OR perform an extra Tackle/Shove challenge OR move one extra hex (including Disengage/Pick-up challenges needed)
----
