== Se lancer / Se Jetter
SE LANCER

C'est un défi spécifique qui peut être effectué seulement une fois par action. Vous devez dépenser des marqueurs de Temps fort lorsque vous entreprenez un défi Se lancer. Le défi réussi vous permet de choisir une des 2 options:
1. Vous déplacez d'un hexagone supplémentaire même si vous avez dépensé tous vos points de mouvement (pas d'autre défi que Désengager ou Ramasser).
*Ou* 2. Exécutez un seul Défi avec un dé supplémentaire. Si vous avez déjà utilisé toutes vos Poussées et/ou Plaquage, vous pouvez en exécuter un autre mais  sans dés en bonus. Cette option met toujours fin à votre tour même si vous avez encore des points de mouvement.

Choisir la 2e option et exécuter un défi Charger/Plaquer vous permet d'ajouter le dé supplémentaire a un de ces défis (pas pour les deux.) Le nombre des marqueurs de Temps fort que vous consacrez à tenter le défi Se lancer est utilisé pour représenter le score d'attribut. Vous pouvez consacrer un Temps fort restant pour remplacer un dé comme normalement..

Se lancer
Attribut:	# de Temps fort utilisé
# de succès nécessaire	1
Modificateur de succès: Aucun
Résultat:
Échec:	Le joueur est sonné. RdS
Nombre de succès insuffisant:	Le joueur est à terre. RdS.
Nombre de succès suffisant:	Le joueur peut effectuer un défi supplémentaire avec un extra-dé OU un tacle/poussée supplémentaire OU bouger d'un hexagone (incluant le désengagement ou le ramassage)
Note: les succès supplémentaires n'apportent pas de Temps fort

----
== Dash challenge
This is a special challenge that may be performed only once an action. You may spend Momentum counters to attempt a Dash challenge to extend your movement, or gain a slight boost to a challenge. A successful Dash challenge lets you choose 1 of 2 options:

Move one extra hex after all Jog Points have been spent (no challenges allowed other than Disengage or Pick-up challenges). OR
Perform a single Challenge with one extra die. If you have already used all of your Shoves and/or performed your one Tackle Challenge, you may perform another one but without the extra dice bonus. This option always ends your turn even if you have Jog points left.
Choosing the 2nd option and performing an available Impact or Tackle challenge allows you to add the extra Challenge dice to one of those challenges (not both). The number of Momentum counters you spend to make the Dash challenge is used as the attribute. You may spend any remaining Momentum to replace dice as normal with a Dash challenge.


Dash challenge table
----
