[[playExample1]]
== Play-by-play-example #1


A Dryad from the Timberline Elf team is taking an action. She is going to tackle the Imp with the ball. She has a 5 paces of Jog remaining after moving into the hex shown in Figure 1. Her next move is to move away from her opponent and move into the hex next to the Imp (movement shown by the yellow arrow) (see figure 1). She rolls a Disengage challenge to get away from the Striker. She rolls 4 challenge dice since her Dodge attribute is 4 and since there are no modifiers she needs only 1 success (Striker's Tackle of 2 - 2) (remember if a challenge is less than 1 success needed than it needs 1). The dice rolls for the Disengage challenge are  (a flop and 2 successes means 1 success). One success means the Disengage is successful and the Dryad now has 4 paces of Jog remaining as the move cost one Jog and the Disengage challenge has no Jog cost.



The Dryad now tries a Shove challenge against the Imp (figure 2). She rolls 4 challenge dice since her Might attribute is 4. She needs 1 success as the Imp's Might is 2 (so its 2-2=0 which means 1 success is needed).
The dice rolls are  (3 successes). Since only 1 success was needed this means the Dryad player now has 2 Momentum counters (3-1). This success means the Imp is pushed back one square in a straight line from the direction of the Shove challenge. The Dryad now has 3 paces of Jog remaining after the Shove challenge.



The Dryad now moves one hex in the direction of the yellow arrow (figure 3) leaving the Dryad with 2 paces of Jog remaining.



Now the Dryad attempts a Tackle challenge against the evasive Imp (figure 4). The Timberline Elf coach realizes that this is a gamble but he feels like the Dryad is ready to come through for the team. The Dryad has a Tackle attribute of 1 so she'll roll just 1 challenge die for the Tackle challenge. She does not need to roll an Impact challenge since her Might is more than the Imp's. She needs 1 success for the Tackle challenge as the Imp has a Dodge of 5 but she has a forward facing standing player from her team adjacent to the Imp and she is tackling the Imp from his rear facing (so 5-2- 1-1=1 success). The die roll is . This would mean the tackle was not a success so she uses one of her 2 Momentum counters to replace this roll. The replacement roll is a . She has now rolled 1  success on the Tackle challenge resulting in a Slide Tackle which places both players  Down. This knocks the elfball loose. She rolls the D6 for the ball's bounce direction and rolls a 5 which means it lands in the hex to the left of the Imp. She now has 1 Momentum counter and 1 pace of Jog remaining.



Next the Dryad spends 1 pace of Jog to stand up (see Figure 5). She has a Grit attribute of 4 so she'll need to spend only one point of Jog to stand (5-4). This leaves her with 1 Momentum counter and she is standing with no Jog remaining. This ends her normal action.

However, the Dryad still has 1 Momentum so she decides to try to extend her turn with a Dash challenge. She spends the one Momentum counter for the Dash challenge so she rolls 1 challenge D6 needing 1 success. The roll is a . Success! The Dash challenge lets her extend her action and she decides to use the move one hex and take a free challenge option to move into the hex with the ball and attempt a Pick-up challenge (see figure 6).



She moves into the hex with the ball (figure 6) and attempts a Pick-up challenge. She needs 1 success to pick up the ball and has a Skill of 2. She rolls which gives her one success and allows her to pick up the ball.



The Timberline Elf coach grins at his demonstration that even a Tackle 1 Dryad can be effective at freeing the ball from his opponent's hands. He has the Dryad slowly stretch her limbs taunting the downed Imp and sets her final facing to protect against tackles and ends her action (figure 7). It is now the opponent's turn and he has to figure out how to get the ball back.
