= REGLES AVANCEES

Les pages que vous venez de parcourir vous ont permis d'abordé les règles indispensables pour jouer un match de elfball. Les règles qui vont suivre vous donnes les détails pour bâtir votre propre équipe et jouer de nombreuses parties faisant ainsi progresser votre jeu.

=== BATIR VOTRE EQUIPE

Quand vous bâtissez votre équipe vous recevez 180 points pour au plus 12 joueurs (Note:votre ligue peut changer cette limite de 180 points). Vous n'êtes pas obligé d'utiliser les 180 points pour construire votre équipe mais vous ne pouvez jamais les dépasser. Chaque nouveau joueur débutant sans aptitude coute 15 points.

Cependant les joueurs ne sont pas les seuls éléments que vous pouvez avoir dans votre équipe. Sur cette page, vous trouverez d'autres soutien professionnel pour votre équipe ou des objets que vous pouvez acheter pour votre équipe et ce qu'il coute en point d'équipe de les ajouter (souvenez vous la valeur de votre équipe ne peut dépasser 180 points).

Tant que votre équipe joue vos joueurs progressent et apprennent de nouvelles aptitudes. Gagner ces aptitudes ajoutent des points à votre équipe. Si le gain de ces aptitudes amène votre équipe au delà des 180 points, vous devez vous débarrassez de quelque chose ou quelqu'un afin de garder le joueur qui a gagné une aptitude. Note: Vous ne pouvez jamais avoir moins de 6 joueurs. À tout moment vous pouvez vous débarrassez de joueurs de votre équipe ( et utiliser leur valeur pour autre chose) ou ajouter un débutant à votre équipe pour le coup habituel de 15 points (une dernière fois, votre équipe ne peut excédé la valeur de 180 points)

=== SOUTIENT

*Arbitre Corrompu* (5 points, 1 permis) : Vous avez payé l'arbitre pour regarder de l'autre coté pendant que votre équipe joue. Avoir un arbitre corrompu vous permet de placer un joueur de Type Monstre dans le cercle de mise en jeu et permet à vos joueurs sans ballon de terminer leur action à l'intérieur de l'un des cercles de but. Toutefois, avant votre première action après la mise en jeu avec un joueur de Type Monstre ou au début d'un tour de votre équipe lorsque vous avez un joueur à l'intérieur d'un cercle de but, lancez un dé de défi. Si vous échoué, le résultat est que l'arbitre ne supporte pas l'infraction plus longtemps. Le joueur en infraction est exclus pour le reste du jeu, votre équipe perd la capacité d'exécuter quoi que ce soit durant ce tour (cela compte comme un RdS) et vous ne pouvez plus briser l'une de ces règles pour le reste de la partie.

*Pom-pom girl* (5 points chaque, 4 permis) : Chaque Pom-pom girl peut être utilisé une fois par test au début d'une action pour ajouter un marquer au compteur de Temps fort.

*Fûts de Zlurpee* (5 points chaque, 2 permis) : Votre équipe peut consacré quelques points à acheter des fûts de Zlurpee et des serveurs. Le Zlurpee est une boisson énergisante disponible dans divers arômes du citron à l'or Nain ou plus exotique du sang de tigre apprécié par les Deadlings. Le Zlurpee aide les joueurs a évité certaine blessures qui les rendraient indisponible pour un Test ou pour le reste du match. Pour chaque Fût dans votre équipe, vous pouvez ajouté un succès à tout défi de Blessures durant le match qui n'est pas en échec et qui n'est pas à 0 succès après avoir utilisé un Temps forts. Chaque Fûts peut être utilisé une fois par Test.

*Potions Magiques* ( 5 points chaque, 3 permis ) : Votre équipe peut dépenser ses points pour s'allouer les services d'alchimistes afin de préparer des potions magiques pour aider votre équipe. Mais utiliser la magie n'est  pas sans risque. Vous pouvez utilisez une ou plusieurs potions sur n'importe quel joueur non présent sur le terrain avant  le placement d'un Test, durant un Test  ou après chaque but. Pour utiliser une potion, lancer deux dés de défi et consultez cet table. Si le jet dit que vous gagnez une aptitude basique ou avancée vous ne pouvez choisir qu'une aptitude d'Attribut. Un joueur ne  peut prendre qu'une potion par match.

GAGNER DES POINTS D'EXPERIENCES ET DES APTITUDES

La plupart des joueurs développent des aptitudes après avoir jouer plusieurs matchs de Elfball. Tandis que beaucoup de joueurs ne se changent jamais en stars, chaque équipe peut avoir la chance d'accueillir le joueur à qui tous les enfants rêvent  de ressembler. Les joueurs gagnent le potentiel pour apprendre de nouvelles aptitudes par les points d'expérience

*Points expériences* : comptabiliser les points d'expérience est assez Simple. À chaque fois que votre équipe marque un but, donnez deux points au buteur et un point à tous les autres joueurs sur le terrain.

*Gagner de nouvelles aptitudes* : Pour chaque tranche de 5 points d'expériences votre joueur peut apprendre une nouvelle aptitude basique ou avancée (i.e. Une aptitude à 5 points, une seconde à 10 points, etc...) un joueur ne peut apprendre une aptitude en dehors du tableau des aptitudes. Un joueur peut apprendre une aptitude après chaque match si il a les points nécessaire. Par exemple, un joueur gagne son 10iéme points d'expériences et 3 match plus tard l'entraineur décide de lui apprendre une nouvelle aptitude basique. Une aptitude apprise ne peut être supprimé.

*Aptitudes basiques et avancées* : chaque attribut et type de joueur donne accès à une aptitude basique et une ou plusieurs aptitudes avancées que chaque joueur peut apprendre quand il a les points d'expériences suffisant. Une aptitude avancée ne peut être apprise que si le joueur a déjà apprise l'aptitude basique de cette attribut.  Une aptitude ne peut être apprise qu'une fois par un joueur. Les aptitudes sont décrites avec leur nom, l'attribut sur lequel elle se base et si elle est basique ou avancée. Tous les joueurs peuvent apprendre une aptitude basé sur un attribut général mais uniquement les joueurs du bon type peuvent apprendre les aptitudes basé sur un type.

include::25b-attribute.adoc[]


----
= ADVANCED RULES

== Team building rules
The previous pages gave you all the rules you need to sit down and play a game of Elfball. The following rules are only intended if you want to create a team and play it over multiple games with it growing and changing as you play.

=== Contruire/Développer votre équipe

=== Building/growing your team
The rules for building your new starting team under the Advanced Rules are slightly different than the Basic Rules. Instead of just picking 10 players for your team you receive 180 points to build your team of up to 12 players (Note: your league may change the 180 point limit if you desire). You do not have to spend all 180 points on building your team but your team can never exceed 180 points. Every new rookie unskilled player for your team costs 15 points.

However players are not the only features you can have on your team. On this page, you'll find other team support professionals or items you can purchase for your team and the points that they cost to add to your team (again remember your team's point value can never exceed 180 points).

As your team plays games your players may learn new abilities as they grow in experience at playing the game. Gaining abilities adds points to your team. If gaining abilities would cause your team to go over 180 points, you need to cut something or someone from your team in order to keep the player gaining the skill. Note: You may never cut your team to less than 6 players. At any point you may cut players from your team (to use their value for something else) or add rookies to your team for their normal 15 points (one last time,
your team cannot exceed 180 in value).

=== Team support
Bribed Referee (5 points - 1 allowed) - You have paid off the referee to look the other way while your team plays. Having a Bribed Referee allows you to set up a player with a Type of Monster in the face-off circle and allows your players without the ball to end an action inside either goal circle hex. However before your first action after the face-off with a Monster Type player or at the start of any turn by your team where you have a player inside a goal circle hex, roll one Challenge die. If you flop, the result is that the referee cannot stand the rule breaking anymore. The rulebreaking player is ejected for the remainder of the game, your team loses the ability to perform anything this turn (this counts as a SiM) and you may not break either of these rules for the remainder of the game.

Cheerleader (5 points each, up to 4 allowed) - Cheerleaders (regardless of race) are great for getting your boys into the game with their encouraging (or disparaging) cheers. Each Cheerleader may be used once per Test at the beginning of an action to add one Momentum counter to the Momentum track.

Zlurpee Kegs (5 points each, up to 2 allowed) - Your team can use some of its points to purchase kegs of Zlurpee and a lovely server. Zlurpee is an energy drink coming in a variety of flavours from the traditional lime, to Dwarven Fool's Gold (ale), to the more exotic Tiger's Blood enjoyed by the Deadlings and denizens of the Siringit Plains. Zurpee helps players shake off injuries that would normally make them miss a Test or the rest of the game. For each Energy Drink Barrel on your team, you may add 1 success to any Injury challenge during the game that you do not Flop and do not roll 0 successes after any Momentum use. Each Keg may be used once per Test.

Magic Potions (5 points each, up to 3 allowed) - Your team can spend its points to hire some alchemists to prepare some magic laced potions to help your team. However using magic is not without risks. You may use one or more potions on any player not on the field before setting up for any Test, during a Test or after the last goal is scored. To use a potion, roll two Challenge dice and consult this table. If the roll says you gain a Basic or  Advanced ability only General Attributes abilities may be gained. Because this is potent stuff, a player may only take one potion per game.

=== Gaining experience points & abilites

Most players develop specialities after playing several games of Elfball. While many players never turn into the superstars of the world, every team might get fortunate and have the next player that every child watching hopes to be like. Players can gain the potential to gain new abilities through Experience Points.

Experience Points: Every time your team scores a goal give the player scoring the goal two Experience Points and every other player on your team that is still on the playing field one ExperiencePoint.

Gaining New Abilities: For every full 5 Experience Points your player has he may learn a  new Basic or Advanced ability (i.e. one ability at 5 points, a second at 10 points, etc.) Players do not have to learn a new skill upon gaining the next plateau for skills. A player can learn a new skill after any game in their career if they have enough Experience Points. For example, a player earns his 10th Experience Point and three games later the coach can choose to have him then learn a new Basic ability if he desires. An ability once  learned cannot be removed.

Basic and Advanced Abilities: Each attribute and player Type has at least one Basic and one or more Advanced abilities that any player can learn once they have the Experience Points to do so. An Advanced ability can only be learned if a player already has the Basic ability for that attribute. Each Basic and Advanced ability on your team add 5 points to your team's points (abilities temporarily gained through magic potions are worth 0 points). A specific ability can be learned only once by a player (i.e. you cannot take Agile twice). Each ability that follows is listed with its name, the attribute it is based on and whether it is Basic or Advanced. Any player can learn a Basic or Advanced general attribute ability. Only players of the specified Type can learn Basic and Advanced type attribute abilities.
----
