[[teamlists]]
= TEAM LISTS
BLACK WIDOWS
The Black Widows are famous in the Elfball circuit. This half-elven all women team is known for their passing game which is one of the strongest in the league. Many a team has been caught off guard when a player falls victim to a Widowmaker attack and the Widows seize that moment to throw the ball to an open Striker who runs in for the easy goal.
￼￼￼
# Allowed Position
0-2 Hunters
0-3 Midfielders
0-4 Strikers
0-2 Throwers 0-1 Widowmaker
Jog Might Tackle Dodge Skill Grit
Type
Hunter Midfielder Striker Thrower Cheater
￼￼￼
6 3 4 6 3 3 6 3 2 6 2 3 6 3 5
3 2 3 3 4 4 3 4 4 1
3 3 2 3 2
￼
￼DEADLINGS
Shambling onto the field, these half-pint sized denizens from the afterlife don't let a little thing like being dead stop them from playing Elfball. While these players barely see over the head of a Imp, they pack some powerful punches. Combined with the power of the Deadwoods, this is one of the most feared teams alive ... in a manner of speaking.
￼￼￼
# Allowed Position
0-2 Deadwood
0-2 Ghouls/Vamplings/
Werelings/Wights 0-2 Mummies/Monsters 0-6 Zombies/Skeletons
Jog Might Tackle Dodge Skill Grit
Type
Monster Undead
Monster Undead
￼￼￼
3 6 5 5 3 3
4 5 4 4 3 4
1 1 3 3
2 1 2 2
5 4
5 6
￼
￼
DESERT DOGS
From the arid Vihktora Desert, the Desert Dogs have found the transition to the more moderate climates an easy one as only the quest for glory on the field consumes their thoughts. The Desert Dogs are a well rounded team made only more fearsome with their Whirling Dervishes. A Dervish has often gone mad from excessive exposure to the sun and desert living. They are specialists at knocking players out of bounds and due to their madness they ignore virtually any injury they suffer.
￼￼￼
# Allowed Position
0-2 Defender 0-2 Dervish 0-4 Midfielders 0-2 Strikers 0-2 Throwers
Jog Might Tackle Dodge Skill Grit
Type
Defender Defender Midfielder Striker Thrower
￼￼￼
5 4 4 7 4 1 6 3 3 6 3 2 6 2 3
2 2 3 1 3 3 4 4 3 4
4 5 3 2 3
￼
￼
DIVINE WIND
To the Far West of the Middle Kingdoms they use Elfball to practice and hone their legendary fighting skills. The team is unique in its level of might and tackling skills mixed with fast scoring ninja.
￼￼￼
# Allowed Position
0-3 Defenders
0-3 Hunters
0-4 Midfielders
0-2 Strikers
Jog Might Tackle Dodge Skill Grit Type
5 4 4 2 2 4 Defender 6 3 4 3 2 3 Hunter 6 3 3 3 3 3 Midfielder 6 3 2 4 4 2 Striker
￼￼
￼
￼
DWARVES
The Dwarves living deep under the mountains of the Middle Kingdoms come in two clans. The Black Rock clan in the east practices sorcery summoning Imps to help them with their labours or punishing clan members by turning them into Centaurs to haul away mining debris. By comparison the western based Thunder Hammer clan are their opposites. They use no magic and live their lives as a united group dedicated to hard work, strong ale and gold (lots and lots of gold.)
￼￼￼
# Allowed Position
0-6 or 0-12* Dwarves
0-2 Dwarven Centaurs 0-4 Hobimps
Jog Might Tackle Dodge Skill Grit
5 4 4 1 3 4
7 4 4 2 1 3
6 2 4 4 3 2 Cheater
Type
￼￼￼
Defender Hunter
* Thunder Hammer teams are composed of only 0-12 Dwarves. Black Rock teams use 0-6 Dwarves along with Hobimps and Dwarven Centaurs.
Page 15
ELFBALL
￼￼￼￼￼￼GNOLLS
The Gnolls are a fierce race known primarily for their hunting skills. They are the long time rivals of the Desert Dogs and use their hunting skills on the field to track down opponents with the ball.
￼￼￼￼￼# Allowed Position
0-4 Hunters 0-2 Midfielders 0-4 Safeties 0-2 Strikers
Jog Might Tackle Dodge Skill Grit Type
6 3 4 3 2 3 Hunter 6 3 3 3 3 3 Midfielder 7 3 3 3 2 3 Safety 6 3 2 4 4 2 Striker
￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼GNOMES
Despite their small size Gnomes are surprisingly tough yet nimble. Gnomes use large robotic contraptions to help them with their mining and have ingeniously adapted them for playing Elfball (however these contraptions are notorious for breaking down). Gnomes are meticulous and never in a hurry to get something done instead of getting it done right. This race is known on the Elfball circuit for being "slow but deadly".
￼￼￼￼￼# Allowed Position Jog Might Tackle Dodge Skill Grit
0-9 Gnomes 5 3 3 4 3 3 0-3 Gnomish Contraptions 5 5 5 3 1 2
Type
Little Guy Monster
￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼MIDDLE KINGDOMS
The Humans of the Middle Kingdoms are a varied group with all of them participating in Elfball. Many teams hire brutish monster mercenaries to add needed tackling muscle to their team. These teams are normally well rounded with a focus on speed and scoring over getting into a brawl with the opposing team.
￼￼￼￼￼# Allowed Position Jog Might Tackle Dodge Skill Grit
Type
Midfielder Monster Safety Striker Thrower
￼￼￼￼￼0-2 Midfielders 6 3 3
0-2 Ogres/Cyclops/Minotaurs 5 5 4
0-3 Safeties 7 3 3
0-3 Strikers 6 3 2 0-2 Throwers 6 2 3
3 3 2 1 3 2 4 4 3 4
3 4 3 2 3
￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼NIGHT ELVES
Night Elves are a dark hearted race and many are mages of some renown. The Night Elf mages summon Imps to help their team. The Imps are extremely quick which allows them to get in position on the field or avoid tackles. They are the perfect disposable resources while the Night Elves run in the goals.
￼￼￼￼￼# Allowed Position
0-2 Hunters 0-8 Imps 0-2 Strikers
Jog Might Tackle Dodge Skill Grit Type
6 3 4 3 2 3 Hunter 7 2 2 5 3 2 LittleGuy 6 3 2 4 4 2 Striker
￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼PHARAOHS OF VIHKTORA
These ancient beings emerged from the old tombs in the Vihktora Desert when their worshippers prayed for divine intervention for an upcoming Elfball tournament. However these beings actually enjoyed the game and decided to stay and deliver divine beat-downs on teams from other lands rather than return to their tombs.
￼￼￼￼￼# Allowed Position
0-2 Defender 0-4 Midfielders 0-1 Safeties 0-1 Striker
0-4 Throwers
Jog Might Tackle Dodge Skill Grit
Type
Defender Midfielder Safety Striker Thrower
￼￼￼￼￼5 4 4 6 3 3 7 3 3 6 3 2 6 2 3
2 2 3 3 3 2 4 4 3 4
4 3 3 2 3
￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼RAZORBACKS
The Calicos Marshlands are a dangerous place. The Razorbacks divided their society into two classes to deal with this danger. The Gruts who perform the day to day work around their settlements and Hunters who gather the food and defend them. Now that certain members have left and starting playing Elfball this division of labour has proved very useful.
￼￼￼￼￼# Allowed Position
0-5 Hunters 0-5 Midfielders 0-2 Swinetaurs
Jog Might Tackle Dodge Skill Grit Type
6 3 4 3 2 3 Hunter 6 3 3 3 3 3 Midfielder 6 4 2 4 2 3 Monster
￼￼￼￼￼￼￼￼￼￼￼￼Page 16
ELFBALL
￼
￼
￼SARCOS
From the Calicos Marshlands, the crocodilian Sarcos have slowly oozed into the Elfball circuit over the last few years. What they lack in speed and throwing skill they excel in leaping both for balls and opponents.
￼￼￼
# Allowed Position
Jog Might Tackle Dodge Skill Grit Type
￼￼￼
6 3 4 3 2 3 Hunter 6 3 3 3 3 3 Midfielder 6 3 2 4 4 2 Striker
0-4 Hunters
0-3 Midfielders
0-4 Strikers
0-1 Terrorpin/Leviathan 4 5 4 2 1 5 Monster
￼
￼
￼
￼SAMHAINO
North of the Calicos Marshlands and on the dark eastern edge of the Westerland Forest is the bleak realm of the Samhaino. Little is known or spoken of this race of creatures of nightmares that share their realm of perpetual gloom with the Deadlings other than the fact that they play a blood-chilling game of Elfball.
￼￼￼
# Allowed Position
0-1 Deadwood 0-4 Hunters 0-4 Midfielders 0-2 Safeties 0-1 Thrower
Jog Might Tackle Dodge Skill Grit
Type
Monster Hunter Midfielder Safety Thrower
￼￼￼
3 6 5 6 3 4 6 3 3 7 3 3 6 2 3
1 1 3 2 3 3 3 2 3 4
5 3 3 3 3
￼
￼
￼￼
SIRINGIT
To the southeast of the Calicos Marshlands lay the grassy plains where the land runs on forever (or so they say). The ani-men of this region have evolved from many different species. When they work together for Elfball they produce a team that excels at a little bit of everything.
￼￼￼
# Allowed Position
0-2 Defenders 0-1 Gorillaur
0-1 Hunter
0-2 Mecat
0-3 Midfielders
0-1 Safety 0-1 Tantor 0-1 Thrower
Jog Might Tackle Dodge Skill Grit
Type
Defender Striker Hunter Little Guy Midfielder Safety Monster Thrower
￼￼￼
5 4 4 6 3 3 6 3 4 7 2 2 6 3 3 7 3 3 4 6 4 6 2 3
2 2 3 4 3 2 5 3 3 3 3 2 2 1 3 4
4 2 3 2 3 3 4 3
￼
￼
￼￼
TIMBERLINE ELVES
The Timberline Elves live in the forests on the edges of the Dwarven mountains. Unlike the Night Elves, the Timberline Elves are hunters and excellent with mountain climbing skills. They work as one with their environment and are fierce when protecting the wooden regions they occupy. Their survival skills and the forest Dryads that assist them make them formidable Elfball opponents.
￼￼￼
# Allowed Position
0-4 Dryads 0-2 Hunters 0-2 Midfielders 0-2 Strikers 0-2 Throwers
Jog Might Tackle Dodge Skill Grit
Type
Defender Hunter Midfielder Striker Thrower
￼￼￼
6 4 1 6 3 4 6 3 3 6 3 2 6 2 3
4 2 3 2 3 3 4 4 3 4
4 3 3 2 3
￼
￼
￼￼
VALKYRIES
Living in the frozen North makes for a tough life. The Valkyries are from a clan of Vikings where the women developed fierce battle skills to maintain and protect the homefront while the men where away on raiding voyages. The Valkyries even have "tamed" fierce Ice Trolls and the savage weremen from the icy mountain heights to give their team some extra punching power.
￼￼￼
# Allowed Position
0-4 Hunters/Weremen 0-1 Ice Troll
0-4 Midfielders
0-2 Strikers
0-1 Throwers
Jog Might Tackle Dodge Skill Grit
Type
Hunter Monster Midfielder Striker Thrower
￼￼￼
6 3 4 4 5 4 6 3 3 6 3 2 6 2 3
3 2 3 1 3 3 4 4 3 4
3 4 3 2 3


ORCS
The race of Orcs were nearly exterminated from the Middle Kingdoms during wars many years ago. Now they live a rough existence in mountains and forests on the western border of Black Rock Ridge. These conditions harden the teams they occasionally form and make them formidable opponents.
￼￼￼￼
# Allowed Position
0-2 Defenders 0-2 Hunters 0-4 Midfielders 0-2 Hobimps 0-1 Throwers 0-1 Troll
Jog Might Tackle Dodge Skill Grit
Type
Defender Hunter Midfielder Cheater Thrower Monster
￼￼￼
5 4 4 6 3 4 6 3 3 6 2 4 6 2 3 4 5 4
2 2 3 2 3 3 4 3 3 4 1 1
4 3 3 2 3 6
￼
￼
￼
RATMEN
Speed kills is the motto of the Ratmen. Based on the western edge of the Siringit Plains, the Ratmen work mostly as message couriers between the races of the Siringit and the Middle Kingdoms with brutish Wrats acting as bodyguards on more critical missions. When the Ratmen field Elfball teams they bring the best of their lightning speed to the game.
￼￼￼￼
# Allowed Position
0-4 Couriers 0-2 Midfielders 0-2 Safeties 0-2 Throwers 0-2 Wrat
Jog Might Tackle Dodge Skill Grit
Type
Striker Midfielder Safety Thrower Defender
￼￼￼
7 2 2 6 3 3 7 3 3 6 2 3 6 4 4
4 4 3 3 3 2 3 4 3 1
2 3 3 3 3
￼￼￼￼￼￼￼￼￼￼
