:authors: Tolvä
:doctitle: ElfBall : Livre des régles, seconde édition. Effort de traduction française
:email: <smur (at) free (dot) fr>
:uri-github-repo: elfball
:icons: font
:source-highlighter: coderay
ifdef::backend-pdf[:notitle:]
ifdef::backend-pdf[]
:pdf-page-size: A4
[discrete]
= {doctitle}
endif::[]

Ce dépot concerne l'effort de traduction en français de la seconde édition des régles d'ElfBall.

== Diffusion

Si vous travaillez ou souhaitez travailler sur la traduction française, faites-nous le savoir, de sorte à ne pas dupliquer le travail.

== Workflow

Pour simplifier la gestion et utiliser pleinement les capacités de Git et Github, la manière la plus directe de collaborer consiste à faire un fork sur Github du dépôt *{uri-github-repo}* sur votre propre compte pour y générer vos modifications, si possible sur une branche thématique (link:TODO.adoc[TODO]).

Ensuite, il suffit de lancer une _pull request_ pour nous avertir que les modifications peuvent être revues et intégrées.

** http://pioupioum.fr/developpement/git-alias-productivite.html

== Références pour la traduction

=== Fichier glossaire

Le fichier glossaire.adoc tente de rassembler les traductions choisies pour les termes spécifiques à ElfBall.
Si d'autres termes nécessitent une uniformisation, il ne faut pas hésiter à les y ajouter.
De même, il est toujours possible de changer les termes déjà renseignés si une meilleure traduction est proposée.

L'uniformisation de la traduction par le respect de ce glossaire est une tâche permanente d'amélioration de la qualité finale du texte.

=== Glossaires généraux sur internet

Les glossaires de traduction disponibles sur Internet, sans être des références dogmatiques donnent des indications sur les termes les plus utilisés dans les documents français.

** http://glossaire.traduc.org/
** http://www.culturecommunication.gouv.fr/Politiques-ministerielles/Langue-francaise-et-langues-de-France/

=== Typographie française

La version française du livre se veut un document valant un document écrit nativement en français. À ce titre, la traduction doit suivre autant que possible les règles de typographie française en vigueur.

Voici ci-dessous quelques liens :

** http://www.dsi.univ-paris5.fr/typo.html
** http://jacques-andre.fr/faqtypo/lessons.pdf

== release notes

link:RELEASE-NOTES.adoc[change log]
