== Mise en Jeu ou face-à-face

Un Test commence toujours par une mise en jeu entre les deux joueurs positionnés dans le cercle central. Chaque entraineurs lancent les dés pour un défi de Mise en jeu. Le joueur avec le plus grand nombre de succès (y compris zéro si votre adversaire est en échec) gagne la mise en jeu. En cas d'égalité, relancer les dés. Continuer à lancer les dés jusqu'à ce qu'un joueur gagne la mise en jeu ou que les deux joueurs échoues. Un joueur qui échoue trébuche et est à terre. Si les deux joueurs échouent, une nouvelle mise en jeu est lancée avec la même configuration de départ pour les deux équipes. Le joueur qui gagne la Mise en jeu prend une décision. Le vainqueur peut soit :

* Avancer de deux hexagones dans le cercle jaune de Mise en jeu tant que les cases sont vides pour tenter soit une poussée soit un plaquage sur son adversaire.
* Ou avancé sur la case contenant la balle pour essayer de la Ramasser.

Si le vainqueur de la mise en jeu a une force inférieur à son adversaire il reçoit un Temps fort pour chaque point de force d'écart avant de tenter son défi.

Après cela, , l'équipe du vainqueur commence son tour normal. Tout joueur (y compris le gagnant de la mise en jeu) est éligible à être déplacé dans le cadre de cette première action. Tout Temps fort obtenu pendant la mise en jeu peut être utilisé pendant cette première action (même si c'est un autre joueur qui effectue l'action)

----
 The face-off
Play for a Test beings with a face-off between the two players set up on the centre circle. Each Team Manager rolls a Face-off challenge. The player with the highest number of successes (including zero if your opponent flopped) has won the face-off. In the event of a tie, roll another face-off. Continue rolling tie-break face-offs until either one player wins or both players flop. A player who flops a face-off challenge has tripped and is placed Down on the field. If both players flop the face-off, a new face-off is started with the
same starting setup for each team. The player who wins the face-off gets a decision. The winner may either:

move up to two hexes as long as the hexes are empty and inside the face-off yellow circle to throw either a Shove or Tackle challenge against his face-off opponent
or advance into the hex with the ball and attempt a Pickup challenge.
If the winning face-off player's Might was less than the opposing player's than he is receives one Momentum counter for each point of Might difference before performing this free challenge from the rush of bettering a stronger opponent. After the free pace(s) of movement and challenge, the team of the winner of the face-off goes first (even if the  face-off winner fails or flops the free challenge). Any player (including the face-off winner) is eligible to be moved as part of this first action and any Momentum earned during the face-off or from the free challenge can be used during this first action (even if a different player than the face-off player performs the first action or the face-off player flopped the free challenge.)
----
