== Play-by-play example #2


The Thunder Mountain Dwarves are playing the Black Widows and the Thunder Mountain ball carrier is about to be surrounded if he cannot get out of trouble (figure 1). In an effort to score the winning goal, the coach calls for a risky passing play. However the  Thunder Hammer coach is hoping to build up a little momentum for his player first and calls for him to shove the biggest threat away from him. Using his superior Might the Dwarf uses a Shove challenge against the Black Widows Widowmaker. The Dwarf's Might is 4 so he'll roll 4 challenge dice. The Widowmaker's Might is 3 and since there is one of her team-mates forward facing and adjacent to the Dwarf he'll need 2 successes for the Shove challenge to be a success (3-2+1).



The dice rolls are . With 3 successes Shove challenge is a success (even earning a point of Momentum) and the Dwarf turns his facing to make the throw (see figure 2).

Now the  coach is faced with a difficult decision. He has 3 paces of Jog left but that will not get him very far. Should he change his plans or go for the risky throw? He decides that he is feeling lucky and decides to go for it and spends the pace of Jog for the Throw challenge leaving him with 2 paces of Jog. The Throw challenge to get to the other Thunder Hammer Dwarf will be based on his Skill attribute of 3 so he'll get 3 dice for the throw. Since he performed the Shove challenge first, he can only throw a maximum of 6 hexes. His Dwarf team-mate is 4 hexes away which is one over half the maximum which means he'll need two extra successes. Add in the Hunter adjacent to him adding an extra needed success and he'll need 4 successes to make the successful pass with only 3 challenge dice. He mutters a choice oath and then a prayer to his coffers of gold at home and rolls the dice. The rolls are . He might have done it! He rolls again for the conditional successes and rolls . This gives him 2 conditional successes and 2 successes for 4 total successes (2+2). The throw is a bit wobbly but he made it!



Now that we know the landing location of the elfball we put the passing string between  the two hexes (figure 3) and see if any opponents can try to intercept. The passing string covers part of the hexes for both the Black Widows Hunter and Midfielder and the opposing coach decides to have the Midfielder attempt an Interception challenge. The  skill of the Midfielder is 3 so she rolls 3 challenge dice and with the modifier from her  forward facing adjacent team-mate she only needs 1 success to intercept the ball (2-1). The dice rolls are  - success! (2-1=1) The Dwarf coach realizes that an interception at this time would ruin his grand plan and uses his one counter of Momentum to force the Black Widows Midfielder to replace one of the success die rolls. The replacement roll is a . This means the final result is 1 success and 2 flops. Since the Midfielder now has more flops than successes, she goes Down from the Interception challenge. This means the Dwarf  team is now clear to try and catch the pass.



The Dwarf trying to catch the ball has a Skill attribute of 3 and so will roll 3 challenge dice for the Catch. Since there are no modifiers, he needs 2 successes in order to catch the  ball. His dice rolls are  . Success! He rolled the 2 successes he needed to catch the ball and now the Dwarf coach can smell victory and practically taste the barrels of ale that await him and his team after they win this game.

Now if the Dwarf coach wanted he could pay the pace of Jog to perform another challenge with the Dwarf that threw the ball but decides that he cannot do much with the two paces of Jog he has left and would rather stay adjacent to the Black Widows Hunter next to him than shove her away. So with that decision the Dwarf coach ends his action. Note: if the Dwarf hypothetically was out of Jog after the Throw challenge, he could not have performed a Dash challenge since he has no Momentum.
