== Se relever
Un joueur qui est tombé ou qui a été jeté à terre est représenté de deux façons sur le terrain de jeu : à terre ou sonné. Dans cet état vous ne pouvez bouger ou tenter un défi sans vous levez. Vous ne pouvez relever qu'un joueur par tour. Vous ne pouvez pas vous relever après un RdS.

A terre: Un joueur à terre n'est pas blessé, mais il est temporairement indisponible. Pour représenter un joueur à terre, placez votre figurine sur le dos à l'endroit où elle a été mise à terre.

Sonné: Un joueur sonné met un moment avant que les effets du coup ne se soient dissipés. Pour représenté un joueur sonné placer la figurine face contre terre dans l'hexagone où elle est  tombée.

Si A terre : dépenser 5 - Courage en Mouvement pour se relever +
Si Sonné : dépenser 8 - Courage en Mouvement pour se relever +
Chaque coéquipier adjacent de face réduit le besoin de 1 +
Chaque adversaire adjacent de face augmente le besoin de 1 +
Si vous n'avez pas les points de mouvement nécessaires vous ne vous relevez pas. Si le nombre de point de Mouvement nécessaire est zéro ou moins alors le joueur peut se relever sans perdre de point de Mouvement.

WARNING: vous ne pouvez pas utiliser de défi Se lancer pour gagner un point de mouvement afin de vous relever.

////
== Standing a player up
Players who have fallen or been knocked down are represented by two states if they are still on the playing field, Down and Dazed. In both states, you may not move out of your hex or perform a challenge until you get up.

Down - A Down player is not hurt, but is temporarily on the ground. To represent a Down player, place the miniature face-up on the field in the hex where he was knocked over.

Dazed - A player who is Dazed needs more time to shake off the effects of his fall or a lot of personal grit or team-mate help to focus enough to get up. To represent a Dazed player, place the miniature face-down in the hex where he has fallen.

A player must be taking an action in order to stand up. If your player is Down he can spend 5 less his Grit attribute in Jog paces to get up to a standing position in the same hex. If your player is Dazed he needs 8 less his Grit attribute in Jog paces to get up to a standing position in the same hex. Each adjacent standing team-mate facing the Down/Dazed player reduces the number of Jog paces needed by one and each adjacent standing opponent facing the Down/Dazed player increases the number of Jog paces by one. You may not get up to a standing position if you don't have enough Jog left. Note: you cannot use a Dash challenge to get an extra point of Jog to stand up. If the amount of Jog needed to stand is zero or less than the player may stand without spending any Jog to do so.
////
