== Pousser
Un joueur réalisant une action peut tenter un nombre de poussée égale à la moitié de son mouvement (arrondi supérieur) par action. Un joueur debout peut tenter de pousser un adversaire debout dans un hexagone adjacent qui lui fait face vers un hexagone en ligne droite si aucun autre joueur n'est dedans. Si cette poussée envois l'adversaire dans un hexagone avec une ligne blanche marquant le bord du terrain ou le but, l'arbitre expulse l'adversaire. Si la poussée envoie l'adversaire dans un hexagone contenant la balle, celle ci est traitée comme une balle qui rebondit.

Pousser
Attribut:	Force
# de succès nécessaire	Force adverse - 2
Modificateur de succès
Pour chaque équipier debout face à votre joueur	-1
Pour chaque adversaire debout face à votre joueur autre que la cible	"+1
"
Pousser un adversaire dans le dos	-1
Résultat:
Échec:	Le joueur est à terre. RdS
Nombre de succès insuffisant:	La poussée échoue. L'adversaire de bouge pas. Vous perdez un point de mouvement pour continuer à bouger ou tenter un autre défi.
Nombre de succès suffisant:	Succès; Vous le poussez avec suffisamment de force pour qu'il bouge d'un hexagone

////
== Shove challenge
A player performing an action may attempt a number of Shove challenges up to half his Jog (rounded up) per an action. A standing player may attempt a Shove challenge against a standing opponent in an adjacent hex that he is facing to move the opponent one hex in a straight line if no other player is in that hex. If this shove forces the opponent into a hex with a white line through it on the edge of the field or around the goal, the referee will eject the opponent. If the shove forces the opponent into a hex with the ball, it is treated as a dropped ball.


Shove challenge table
////
